version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: '06:00'
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
    groups:
      npm-deps:
        update-types: [minor, patch]
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '06:05'
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
